### ISSUE TITLE
Section <templates> is not used in <match **> of opensearch plugin

### ISSUE THREAD

**Issue by ng-bsy** [fluent/fluent-plugin-opensearch#135]
- [x] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

#### Steps to replicate

```yaml
- match:
    $tag: '**'
    $type: opensearch
    scheme: https
    ssl_verify: false
    hosts: oshost01,oshost02
    user: XXXX
    password: XXXX
    logstash_format: false
    index_name: fluentd.${tag}
    templates:
      fluentd: '/etc/fluent/os_index_templates/fluentd.json'
```

`[warn]: section <templates> is not used in <match **> of opensearch plugin`

#### Expected Behavior or What you need to ask

I expect to not read the warning message and the opensearch plugin to use the provided templates

#### Using Fluentd and OpenSearch plugin versions

* Ubuntu 22.04 LTS
* Docker fluentd:v1.16-1
* fluentd 1.16.2
* fluent-plugin-opensearch 1.1.4
* OpenSearch version 2.5
* OpenSearch template
```json
{
  "index_patterns" : [
    "fluentd.*"
  ],
  "priority": 10,
  "data_stream": {}
}
```
