### ISSUE TITLE
How to connect to a secure opensearch node

### ISSUE THREAD

**Issue by lukadriel7** [fluent/fluent-plugin-opensearch#23]
(check apply)
- [x] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)

#### Problem
Hello, I previously used the fluent-plugin-elasticsearch to connect to amazon open distro for elasticsearch. I decided to move to opensearch and this plugin but I can't seem to be able to connect to my opensearch node with fluentd. I keep getting the same connection refused error `[Faraday::ConnectionFailed] Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED) {:host=>"localhost", :port=>9200, :scheme=>"https", :user=>"admin", :password=><REDACTED>, :protocol=>"https"}`

I can connect to the dashboard without any issue.
I tried with my previous configuration and tried changing some things but to no avails. I use self signed certificate expiring in 2031.
Unfortunately, I couldn't find any detailed tutorial about this.
...

#### Steps to replicate
Here are my configuration files

opensearch.yml

```yaml
plugins.security.ssl.transport.pemcert_filepath: admin.pem
plugins.security.ssl.transport.pemkey_filepath: admin-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: admin.pem
plugins.security.ssl.http.pemkey_filepath: admin-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.allow_default_init_securityindex: true
plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled:
  ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
opendistro_security.audit.config.disabled_rest_categories: NONE
opendistro_security.audit.config.disabled_transport_categories: NONE
```
fluent.conf
```fluentd
# fluentd/conf/fluent.conf

<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<source>
  @type http
  port 9880
  bind 0.0.0.0
  body_size_limit 32m
  keepalive_timeout 10s
</source>

<match *.**>
@type copy



<store>

<transport tls>
    cert_path /fluentd/etc/certs/root-ca.pem
    private_key_path /fluentd/etc/certs/root-ca-key.pem
</transport>

  @type opensearch
  host localhost
  port 9200
  user admin
  password admin
  scheme https
  ssl_verify false
  ssl_max_version TLSv1_2
  ssl_min_version TLSv1_2
  logstash_format true
  logstash_prefix fluentd
  logstash_dateformat %Y%m%d
  include_tag_key true
  type_name access_log
  tag_key @log_name
  flush_interval 10s
  with_transporter_log true
  @log_level debug
</store>

<store>
  @type stdout
</store>
</match>
```

docker-compose
```docker-compose
version: "3.9"
services:
  opensearch:
    image: opensearchproject/opensearch
    container_name: opensearch
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - network.host=0.0.0.0
    
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536

    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch/config/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./opensearch/config/admin.pem:/usr/share/opensearch/config/admin.pem
      - ./opensearch/config/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      - ./opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
  dashboard:
    image: opensearchproject/opensearch-dashboards
    container_name: dashboard
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: https://opensearch:9200
    depends_on:
      - "opensearch"
  fluentd:
    image: lukadriel/fluentsearch
    container_name: fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
      - 9880:9880
    volumes:
      - ./fluentd/etc:/fluentd/etc
      - ./opensearch/config/root-ca.pem:/fluentd/etc/certs/root-ca.pem
      - ./opensearch/config/root-ca-key.pem:/fluentd/etc/certs/root-ca-key.pem
      - ./opensearch/config/admin.pem:/fluentd/etc/certs/admin.pem
      - ./opensearch/config/admin-key.pem:/fluentd/etc/certs/admin-key.pem
    depends_on:
      - "opensearch"

networks:
  default:
    external: true
    name: sih-network
volumes:
  opensearch-data:
```

#### Expected Behavior or What you need to ask
I am asking for some help configuring fluentd connection to opensearch

...

#### Using Fluentd and OpenSearch plugin versions

* Windows 10
* Docker
* Fluentd v1.14
* OpenSearch plugin version: 1.0.1
* OpenSearch version: 1.2.4
